apiVersion: v1
kind: ServiceAccount
metadata:
  name: experiment-sa
  labels:
    name: experiment-sa
---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: experiment
  labels:
    name: experiment
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: experiment
  labels:
    name: experiment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: experiment
subjects:
- kind: ServiceAccount
  name: experiment-sa
  namespace: default
